version: 2
jobs:
  build:
    docker:
      - image: kitalab/library-py:latest

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date
